version: '2'
services:
# Recipe Service container
    recipe-service:
        build: ./recipe-service
        restart: unless-stopped
        volumes:
            - ./recipe-service:/server/http
            - ./data/keys:/server/keys
            - ./data/logs:/server/logs
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - postgres
        env_file:
            - ./recipe-service/.env
# Postgres container for Recipe Service
    postgres:
        image: onjin/alpine-postgres:9.5
        restart: unless-stopped
        ports:
            - "5432:5432"
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
        environment:
            LC_ALL: C.UTF-8
            POSTGRES_USER: hellofresh
            POSTGRES_PASSWORD: hellofresh
            POSTGRES_DB: hellofresh
# OAuth Service container
    oauth-service:
        build: ./oauth-service
        restart: unless-stopped
        volumes:
            - ./oauth-service:/server/http
            - ./data/keys:/server/keys
            - ./data/logs:/server/logs
        ports:
            - "8001:80"
            - "4431:443"
        depends_on:
            - postgres-oauth
        env_file:
            - ./oauth-service/.env
# Postgres for OAuth container
    postgres-oauth:
        image: onjin/alpine-postgres:9.5
        restart: unless-stopped
        ports:
            - "54321:5432"
        volumes:
            - ./data/postgres-auth:/var/lib/postgresql/data
        environment:
            LC_ALL: C.UTF-8
            POSTGRES_USER: hellofresh
            POSTGRES_PASSWORD: hellofresh
            POSTGRES_DB: hellofresh
# Redis container for Message Queue
    redis:
        image: sickp/alpine-redis:3.2.2
        restart: unless-stopped
        ports:
            - "6379:6379"
