version: '2'
services:
# Recipe Service container 
    recipe-service:
        build: ./recipe-service
        restart: unless-stopped
        volumes:
            - ./recipe-service:/server/http
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - postgres
            - redis
        env_file:
            - ./recipe-service/.env
# Postgres container
    postgres:
        image: onjin/alpine-postgres:9.5
        restart: unless-stopped
        ports:
            - "5432:5432"
        environment:
            LC_ALL: C.UTF-8
            POSTGRES_USER: hellofresh
            POSTGRES_PASSWORD: hellofresh
            POSTGRES_DB: hellofresh
# Redis container            
    redis:
        image: sickp/alpine-redis:3.2.2
        restart: unless-stopped
        ports:
            - "6379:6379"

