--
-- PostgreSQL database dump
--

-- Dumped from database version 9.5.6
-- Dumped by pg_dump version 9.5.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: plpgsql; Type: EXTENSION; Schema: -; Owner: 
--

CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;


--
-- Name: EXTENSION plpgsql; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';


SET search_path = public, pg_catalog;

SET default_tablespace = '';

SET default_with_oids = false;

--
-- Name: phinxlog; Type: TABLE; Schema: public; Owner: hellofresh
--

CREATE TABLE phinxlog (
    version bigint NOT NULL,
    migration_name character varying(100),
    start_time timestamp without time zone,
    end_time timestamp without time zone,
    breakpoint boolean DEFAULT false NOT NULL
);


ALTER TABLE phinxlog OWNER TO hellofresh;

--
-- Name: ratings; Type: TABLE; Schema: public; Owner: hellofresh
--

CREATE TABLE ratings (
    rating integer NOT NULL,
    recipe_id integer NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


ALTER TABLE ratings OWNER TO hellofresh;

--
-- Name: recipes; Type: TABLE; Schema: public; Owner: hellofresh
--

CREATE TABLE recipes (
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    description text NOT NULL,
    prep_time integer NOT NULL,
    difficulty integer NOT NULL,
    vegetarian boolean DEFAULT false NOT NULL,
    rating real DEFAULT '0'::real NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone
);


ALTER TABLE recipes OWNER TO hellofresh;

--
-- Name: recipes_id_seq; Type: SEQUENCE; Schema: public; Owner: hellofresh
--

CREATE SEQUENCE recipes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE recipes_id_seq OWNER TO hellofresh;

--
-- Name: recipes_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: hellofresh
--

ALTER SEQUENCE recipes_id_seq OWNED BY recipes.id;


--
-- Name: id; Type: DEFAULT; Schema: public; Owner: hellofresh
--

ALTER TABLE ONLY recipes ALTER COLUMN id SET DEFAULT nextval('recipes_id_seq'::regclass);


--
-- Data for Name: phinxlog; Type: TABLE DATA; Schema: public; Owner: hellofresh
--

COPY phinxlog (version, migration_name, start_time, end_time, breakpoint) FROM stdin;
20181029174721	CreateRecipes	2018-11-07 01:49:06	2018-11-07 01:49:06	f
20181029181737	CreateRatings	2018-11-07 01:49:06	2018-11-07 01:49:06	f
\.


--
-- Data for Name: ratings; Type: TABLE DATA; Schema: public; Owner: hellofresh
--

COPY ratings (rating, recipe_id, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: recipes; Type: TABLE DATA; Schema: public; Owner: hellofresh
--

COPY recipes (id, name, description, prep_time, difficulty, vegetarian, rating, created_at, updated_at, deleted_at) FROM stdin;
\.


--
-- Name: recipes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: hellofresh
--

SELECT pg_catalog.setval('recipes_id_seq', 1, false);


--
-- Name: phinxlog_pkey; Type: CONSTRAINT; Schema: public; Owner: hellofresh
--

ALTER TABLE ONLY phinxlog
    ADD CONSTRAINT phinxlog_pkey PRIMARY KEY (version);


--
-- Name: recipes_pkey; Type: CONSTRAINT; Schema: public; Owner: hellofresh
--

ALTER TABLE ONLY recipes
    ADD CONSTRAINT recipes_pkey PRIMARY KEY (id);


--
-- Name: ratings_recipe_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: hellofresh
--

ALTER TABLE ONLY ratings
    ADD CONSTRAINT ratings_recipe_id_fkey FOREIGN KEY (recipe_id) REFERENCES recipes(id) ON DELETE CASCADE;


--
-- Name: public; Type: ACL; Schema: -; Owner: postgres
--

REVOKE ALL ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON SCHEMA public FROM postgres;
GRANT ALL ON SCHEMA public TO postgres;
GRANT ALL ON SCHEMA public TO PUBLIC;


--
-- PostgreSQL database dump complete
--

